### ISSUE TITLE
Prediction Error for handling SMILES for cyclobutane stereoisomers

### ISSUE THREAD

**Issue by lkulloa** [jensengroup/ESNUEL#3]
When inputting this SMILES string:  [NH-][C@H]1C[C@H](NC(OC(C)(C)C)=O)C1 
The webtool returns this error:  Prediction ERROR! Please submit an issue on GitHub with ID: ffbade4b0a82ef44195598db220bf988

The webtool works for the neutral molecule with stereochemistry specified:  N[C@H]1C[C@H](NC(OC(C)(C)C)=O)C1
Also works for the anionic molecule with stereochemistry specified with the other nitrogen deprotonated:  N[C@H]1C[C@H]([N-]C(OC(C)(C)C)=O)C1
It also works when I don't specify stereochemistry and deprotonate the desired nitrogen.  However, when I click to see the 3D structure, it had arbitrarily run the calculation with the cis diastereomer (I want the trans):  [NH-]C1CC(NC(OC(C)(C)C)=O)C1

Any help you can provide for fixing this error would be much appreciated!  I really like the web tool, thank you!

**Comment by NicolaiRee** [comment]
There was a convergence issue in the underlying single-point QM calculation for obtaining the CM5 charges. I ran an xTB optimization of the structure, so now you can see the results on: https://esnuel.org/MLresults/ffbade4b0a82ef44195598db220bf988

However, the ML version is not yet optimized for molecules with a formal charge. I would instead recommend you to use the xTB version by selecting "xTB" instead of "ML":
![Screenshot 2024-09-02 at 13 07 30](https://github.com/user-attachments/assets/7264ac76-5559-43d3-a78a-06c1bc9b96eb)
